# Generated by Django 6.0.1 on 2026-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="token",
            field=models.IntegerField(default=1000, help_text="用户虚拟货币余额"),
        ),
    ]
