# Generated by Django 6.0.1 on 2026-03-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="谱师名义（展示用名称）",
                max_length=50,
            ),
        ),
    ]
