# Generated by Django 6.0.1 on 2026-01-30 15:01

import django.db.models.deletion
import songs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='公告标题', max_length=200)),
                ('content', models.TextField(help_text='公告内容（支持 Markdown）')),
                ('category', models.CharField(choices=[('news', '新闻'), ('event', '活动'), ('notice', '通知')], default='news', help_text='公告分类', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='优先级，越大越靠前')),
                ('is_pinned', models.BooleanField(default=False, help_text='是否置顶')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-is_pinned', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner 标题', max_length=100)),
                ('content', models.TextField(help_text='Banner 描述内容')),
                ('image_url', models.CharField(blank=True, help_text='背景图片 URL（可选）', null=True)),
                ('link', models.URLField(blank=True, help_text='点击跳转链接（可选）', null=True)),
                ('button_text', models.CharField(default='了解更多', help_text='按钮文本', max_length=50)),
                ('color', models.CharField(default='#409EFF', help_text='背景色', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='优先级，越大越靠前')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiddingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_type', models.CharField(choices=[('song', '歌曲竞标'), ('chart', '谱面竞标')], default='song', help_text='竞标类型：歌曲竞标或谱面竞标', max_length=20)),
                ('name', models.CharField(help_text='竞标轮次名称', max_length=100)),
                ('status', models.CharField(choices=[('pending', '待开始'), ('active', '进行中'), ('completed', '已完成')], default='pending', help_text='竞标状态', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('started_at', models.DateTimeField(blank=True, help_text='开始时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('allow_public_view', models.BooleanField(default=True, help_text='如果关闭，只有管理员能看到竞标列表，普通用户（包括竞标者）无法查看。', verbose_name='允许公开查看竞标')),
            ],
            options={
                'verbose_name': '竞标轮次',
                'verbose_name_plural': '竞标轮次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='阶段名称，如"竞标期"、"制谱期"', max_length=100)),
                ('phase_key', models.CharField(help_text='唯一标识符，用于权限绑定。如 bidding、mapping、peer_review', max_length=50, unique=True)),
                ('description', models.TextField(help_text='阶段描述，显示在主页时间轴')),
                ('submissions_type', models.CharField(choices=[('songs', '歌曲数'), ('charts', '谱面数')], default='songs', help_text='该阶段统计的作品类型（显示在首页）', max_length=20)),
                ('start_time', models.DateTimeField(help_text='阶段开始时间')),
                ('end_time', models.DateTimeField(help_text='阶段结束时间')),
                ('order', models.PositiveIntegerField(default=0, help_text='显示顺序（从小到大）')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此阶段')),
                ('page_access', models.JSONField(default=songs.models.get_default_page_access, help_text='页面访问权限配置，如 {"songs": true, "charts": false, "profile": true, "eval": true}（注：首页、登录、注册页总是可访问）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '比赛阶段',
                'verbose_name_plural': '比赛阶段',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BidResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_type', models.CharField(choices=[('song', '歌曲竞标'), ('chart', '谱面竞标')], default='song', help_text='分配类型：歌曲或谱面', max_length=20)),
                ('bid_amount', models.IntegerField(help_text='最终成交的竞标金额')),
                ('allocation_type', models.CharField(choices=[('win', '中标'), ('random', '随机分配')], default='win', help_text='分配类型（中标或随机分配）', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True, help_text='分配时间')),
                ('bidding_round', models.ForeignKey(help_text='所属竞标轮次', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='songs.biddinground')),
                ('user', models.ForeignKey(help_text='获得歌曲或谱面的用户', on_delete=django.db.models.deletion.CASCADE, related_name='bid_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '竞标结果',
                'verbose_name_plural': '竞标结果',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('part_submitted', '半成品'), ('final_submitted', '完稿'), ('under_review', '评分中'), ('reviewed', '已评分')], default='part_submitted', help_text='谱面状态', max_length=20)),
                ('designer', models.CharField(default='未填写', help_text='谱师名义', max_length=100)),
                ('audio_file', models.FileField(blank=True, help_text='谱面对应音频文件', null=True, upload_to=songs.models.get_chart_audio_filename)),
                ('cover_image', models.ImageField(blank=True, help_text='谱面封面图片', null=True, upload_to=songs.models.get_chart_cover_filename)),
                ('background_video', models.FileField(blank=True, help_text='谱面背景视频（可选）', null=True, upload_to=songs.models.get_chart_video_filename)),
                ('chart_file', models.FileField(blank=True, help_text='谱面文件（maidata.txt）', null=True, upload_to=songs.models.get_chart_filename)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='提交时间', null=True)),
                ('review_completed_at', models.DateTimeField(blank=True, help_text='评分完成时间', null=True)),
                ('review_count', models.IntegerField(default=0, help_text='收到的评分数')),
                ('total_score', models.IntegerField(default=0, help_text='总评分（用于快速计算平均分）')),
                ('average_score', models.FloatField(default=0.0, help_text='平均分（0-50）')),
                ('is_part_one', models.BooleanField(default=True, help_text='是否是第一部分谱面（True=第一部分，False=第二部分）')),
                ('bid_result', models.ForeignKey(blank=True, help_text='对应的竞标结果（第一部分必需，第二部分可选）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='songs.bidresult')),
                ('bidding_round', models.ForeignKey(help_text='所属竞标轮次', on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='songs.biddinground')),
                ('completion_bid_result', models.ForeignKey(blank=True, help_text='第二轮竞标获得的一部分，用于续写', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_charts', to='songs.bidresult')),
                ('part_one_chart', models.OneToOneField(blank=True, help_text='如果是第二部分，指向对应的第一部分谱面', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_two_chart', to='songs.chart')),
                ('user', models.ForeignKey(help_text='谱面创建者', on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '谱面',
                'verbose_name_plural': '谱面',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bidresult',
            name='chart',
            field=models.ForeignKey(blank=True, help_text='分配的谱面（仅当bid_type=chart时使用）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_results', to='songs.chart'),
        ),
        migrations.AddField(
            model_name='biddinground',
            name='competition_phase',
            field=models.ForeignKey(blank=True, help_text='所属比赛阶段（可选，用于与比赛流程关联）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_rounds', to='songs.competitionphase'),
        ),
        migrations.CreateModel(
            name='PeerReviewAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待评分'), ('completed', '已完成')], default='pending', help_text='任务状态', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True, help_text='分配时间')),
                ('bidding_round', models.ForeignKey(help_text='所属竞标轮次', on_delete=django.db.models.deletion.CASCADE, related_name='peer_review_allocations', to='songs.biddinground')),
                ('chart', models.ForeignKey(help_text='被评分的谱面', on_delete=django.db.models.deletion.CASCADE, related_name='review_allocations', to='songs.chart')),
                ('reviewer', models.ForeignKey(help_text='评分者', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_peer_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '互评分配',
                'verbose_name_plural': '互评分配',
                'ordering': ['allocated_at'],
                'unique_together': {('reviewer', 'chart')},
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='评分')),
                ('comment', models.TextField(blank=True, help_text='评论（可选）', null=True)),
                ('favorite', models.BooleanField(default=False, help_text='是否标记为喜欢')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='评分时间')),
                ('chart', models.ForeignKey(help_text='被评分的谱面', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='songs.chart')),
                ('reviewer', models.ForeignKey(help_text='评分者', on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_reviews', to=settings.AUTH_USER_MODEL)),
                ('allocation', models.OneToOneField(blank=True, help_text='对应的分配任务（系统分配的任务有allocation，额外评分没有）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='songs.peerreviewallocation')),
            ],
            options={
                'verbose_name': '互评记录',
                'verbose_name_plural': '互评记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='歌曲标题', max_length=100)),
                ('audio_file', models.FileField(help_text='音频文件', upload_to=songs.models.get_audio_filename)),
                ('cover_image', models.ImageField(blank=True, help_text='封面图片（可选）', null=True, upload_to=songs.models.get_cover_filename)),
                ('background_video', models.FileField(blank=True, help_text='背景视频（bg.mp4或pv.mp4，最大20MB，可选）', null=True, upload_to=songs.models.get_video_filename)),
                ('netease_url', models.URLField(blank=True, help_text='网易云音乐链接（可选）', null=True)),
                ('audio_hash', models.CharField(db_index=True, help_text='音频文件 SHA256 hash，用于识别重复', max_length=64)),
                ('file_size', models.IntegerField(help_text='音频文件大小（字节）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='song',
            field=models.ForeignKey(help_text='谱面对应的歌曲', on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='songs.song'),
        ),
        migrations.AddField(
            model_name='bidresult',
            name='song',
            field=models.ForeignKey(blank=True, help_text='分配的歌曲（仅当bid_type=song时使用）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_results', to='songs.song'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_type', models.CharField(choices=[('song', '歌曲竞标'), ('chart', '谱面竞标')], default='song', help_text='竞标类型：歌曲或谱面', max_length=20)),
                ('amount', models.IntegerField(help_text='竞标金额（代币）')),
                ('is_dropped', models.BooleanField(default=False, help_text='是否已被drop（被更高出价者获得）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='竞标时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('user', models.ForeignKey(help_text='竞标用户', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('bidding_round', models.ForeignKey(help_text='所属竞标轮次', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='songs.biddinground')),
                ('chart', models.ForeignKey(blank=True, help_text='目标谱面（仅当bid_type=chart时使用）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='songs.chart')),
                ('song', models.ForeignKey(blank=True, help_text='目标歌曲（仅当bid_type=song时使用）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='songs.song')),
            ],
            options={
                'verbose_name': '竞标',
                'verbose_name_plural': '竞标',
                'ordering': ['-amount', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('bidding_round', 'user', 'song')},
        ),
    ]
