# Generated by Django 6.0.1 on 2026-01-16 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiddingRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="竞标轮次名称", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("active", "进行中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        help_text="竞标状态",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="开始时间", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="完成时间", null=True),
                ),
            ],
            options={
                "verbose_name": "竞标轮次",
                "verbose_name_plural": "竞标轮次",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="song",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(help_text="竞标金额（代币）")),
                (
                    "is_dropped",
                    models.BooleanField(
                        default=False, help_text="是否已被drop（歌曲被更高出价者获得）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="竞标时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间"),
                ),
                (
                    "song",
                    models.ForeignKey(
                        help_text="目标歌曲",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="songs.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="竞标用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bidding_round",
                    models.ForeignKey(
                        help_text="所属竞标轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="songs.biddinground",
                    ),
                ),
            ],
            options={
                "verbose_name": "竞标",
                "verbose_name_plural": "竞标",
                "ordering": ["-amount", "-created_at"],
                "unique_together": {("bidding_round", "user", "song")},
            },
        ),
        migrations.CreateModel(
            name="BidResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_amount", models.IntegerField(help_text="最终成交的竞标金额")),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[("win", "中标"), ("random", "随机分配")],
                        default="win",
                        help_text="分配类型（中标或随机分配）",
                        max_length=20,
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(auto_now_add=True, help_text="分配时间"),
                ),
                (
                    "bidding_round",
                    models.ForeignKey(
                        help_text="所属竞标轮次",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="songs.biddinground",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        help_text="分配的歌曲",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_results",
                        to="songs.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="获得歌曲的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "竞标结果",
                "verbose_name_plural": "竞标结果",
                "ordering": ["-allocated_at"],
                "unique_together": {("bidding_round", "user", "song")},
            },
        ),
    ]
