# Generated by Django 6.0.1 on 2026-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0007_competitionphase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionphase",
            name="page_access",
            field=models.JSONField(
                default=dict,
                help_text='页面访问权限配置，如 {"songs": true, "charts": false, "profile": true}（注：首页、登录、注册页总是可访问）',
            ),
        ),
    ]
