# Generated by Django 6.0.1 on 2026-01-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0009_competitionphase_submissions_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="biddinground",
            name="bidding_type",
            field=models.CharField(
                choices=[("song", "歌曲竞标"), ("chart", "谱面竞标")],
                default="song",
                help_text="竞标类型：歌曲竞标或谱面竞标",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="biddinground",
            name="competition_phase",
            field=models.ForeignKey(
                blank=True,
                help_text="所属比赛阶段（可选，用于与比赛流程关联）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidding_rounds",
                to="songs.competitionphase",
            ),
        ),
    ]
