# Generated by Django 6.0.1 on 2026-01-18 03:03

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0010_biddinground_bidding_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chart",
            name="chart_id_external",
        ),
        migrations.RemoveField(
            model_name="chart",
            name="chart_url",
        ),
        migrations.AddField(
            model_name="chart",
            name="chart_file",
            field=models.FileField(
                blank=True,
                help_text="谱面文件（maidata.txt）",
                null=True,
                upload_to=songs.models.get_chart_filename,
            ),
        ),
        migrations.AlterField(
            model_name="chart",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "已提交"),
                    ("under_review", "评分中"),
                    ("reviewed", "已评分"),
                ],
                default="submitted",
                help_text="谱面状态",
                max_length=20,
            ),
        ),
    ]
