# Generated by Django 6.0.1 on 2026-01-18 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0011_chart_local_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 统一竞标系统迁移：直接删除 Second 系列模型，避免在SQLite上多步骤移除字段导致的状态不一致
        migrations.AlterUniqueTogether(
            name="bid",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="bidresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bid",
            name="bid_type",
            field=models.CharField(
                choices=[("song", "歌曲竞标"), ("chart", "谱面竞标")],
                default="song",
                help_text="竞标类型：歌曲或谱面",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="chart",
            field=models.ForeignKey(
                blank=True,
                help_text="目标谱面（仅当bid_type=chart时使用）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="songs.chart",
            ),
        ),
        migrations.AddField(
            model_name="bidresult",
            name="bid_type",
            field=models.CharField(
                choices=[("song", "歌曲竞标"), ("chart", "谱面竞标")],
                default="song",
                help_text="分配类型：歌曲或谱面",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bidresult",
            name="chart",
            field=models.ForeignKey(
                blank=True,
                help_text="分配的谱面（仅当bid_type=chart时使用）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_results",
                to="songs.chart",
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="is_dropped",
            field=models.BooleanField(
                default=False, help_text="是否已被drop（被更高出价者获得）"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="song",
            field=models.ForeignKey(
                blank=True,
                help_text="目标歌曲（仅当bid_type=song时使用）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="songs.song",
            ),
        ),
        migrations.AlterField(
            model_name="bidresult",
            name="song",
            field=models.ForeignKey(
                blank=True,
                help_text="分配的歌曲（仅当bid_type=song时使用）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_results",
                to="songs.song",
            ),
        ),
        migrations.AlterField(
            model_name="bidresult",
            name="user",
            field=models.ForeignKey(
                help_text="获得歌曲或谱面的用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="SecondBid",
        ),
        migrations.DeleteModel(
            name="SecondBiddingRound",
        ),
        migrations.DeleteModel(
            name="SecondBidResult",
        ),
    ]
