# Generated by Django 6.0.1 on 2026-01-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0012_remove_secondbiddinground_first_bidding_round_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="designer",
            field=models.CharField(
                default="未填写",
                help_text="谱师名义",
                max_length=100,
            ),
        ),
    ]
