# Generated by Django 6.0.1 on 2026-01-18 00:00

import django.db.models.deletion
from django.db import migrations, models
import songs.models


def map_status_forward(apps, schema_editor):
    Chart = apps.get_model('songs', 'Chart')
    Chart.objects.filter(status='submitted').update(status='part_submitted')


def map_status_backward(apps, schema_editor):
    Chart = apps.get_model('songs', 'Chart')
    Chart.objects.filter(status='part_submitted').update(status='submitted')


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_chart_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='audio_file',
            field=models.FileField(
                blank=True,
                help_text='谱面对应音频文件',
                null=True,
                upload_to=songs.models.get_chart_audio_filename,
            ),
        ),
        migrations.AddField(
            model_name='chart',
            name='cover_image',
            field=models.ImageField(
                blank=True,
                help_text='谱面封面图片',
                null=True,
                upload_to=songs.models.get_chart_cover_filename,
            ),
        ),
        migrations.AlterField(
            model_name='chart',
            name='status',
            field=models.CharField(
                choices=[
                    ('part_submitted', '半成品'),
                    ('final_submitted', '完稿'),
                    ('under_review', '评分中'),
                    ('reviewed', '已评分'),
                ],
                default='part_submitted',
                help_text='谱面状态',
                max_length=20,
            ),
        ),
        migrations.RunPython(map_status_forward, map_status_backward),
    ]
