# Generated by Django 6.0.1 on 2026-01-18 08:16

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0014_chart_stage_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="background_video",
            field=models.FileField(
                blank=True,
                help_text="背景视频（bg.mp4或pv.mp4，最大20MB，可选）",
                null=True,
                upload_to=songs.models.get_video_filename,
            ),
        ),
    ]
