# Generated by Django 6.0.1 on 2026-01-18 16:09

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0016_chart_background_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionphase",
            name="page_access",
            field=models.JSONField(
                default=songs.models.get_default_page_access,
                help_text='页面访问权限配置，如 {"songs": true, "charts": false, "profile": true, "eval": true}（注：首页、登录、注册页总是可访问）',
            ),
        ),
    ]
