# Generated by Django 6.0.1 on 2026-01-18 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0017_alter_competitionphase_page_access"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="peerreviewallocation",
            unique_together={("reviewer", "chart")},
        ),
        migrations.AlterField(
            model_name="peerreview",
            name="allocation",
            field=models.OneToOneField(
                blank=True,
                help_text="对应的分配任务（系统分配的任务有allocation，额外评分没有）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="songs.peerreviewallocation",
            ),
        ),
        migrations.AlterField(
            model_name="peerreview",
            name="bidding_round",
            field=models.ForeignKey(
                blank=True,
                help_text="所属竞标轮次（可选，互评不一定绑定轮次）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peer_reviews",
                to="songs.biddinground",
            ),
        ),
    ]
