# Generated by Django 6.0.1 on 2026-01-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0018_alter_peerreviewallocation_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peerreview",
            name="bidding_round",
        ),
    ]
